source 'https://rubygems.org'

# Bundle edge Rails instead: gem 'rails', github: 'rails/rails'
gem 'rails'

# Use sqlite3 as the database for Active Record
gem 'sqlite3'

gem 'rspec'
gem 'rspec-rails'

gem 'devise'

group :test do
	gem 'factory_girl_rails', "~> 4.0"

	gem 'byebug'

	gem 'database_cleaner'

	gem 'faker'
end