# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 64b445653a2a3f68593638c15e91e56278de888805ac3aa802e0c52a351c3874e7ba067ca10356d8503e730985a087adb69ec39d6172beda1227aa05c392091b

test:
  secret_key_base: 6ff9568afec8cb516518586d25123b19906d37e9876244d64893ceef882f25eaec80645f9ddcf186a148dc3e495e29cd22efe3e842d9a5b1d3266be9348d7582

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
